# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xatPrivat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fxatPrivat.proto\">\n\x11\x43onnectionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63lient_address\x18\x02 \x01(\t\"%\n\x12\x43onnectionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\">\n\x0b\x43hatMessage\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\t\x12\r\n\x05to_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1d\n\nMessageAck\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x08\x43lientID\x12\x11\n\tclient_id\x18\x01 \x01(\t2\x9c\x01\n\x0b\x43hatService\x12\x34\n\x07\x43onnect\x12\x12.ConnectionRequest\x1a\x13.ConnectionResponse\"\x00\x12*\n\x0bSendMessage\x12\x0c.ChatMessage\x1a\x0b.MessageAck\"\x00\x12+\n\x0eReceiveMessage\x12\t.ClientID\x1a\x0c.ChatMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xatPrivat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTIONREQUEST']._serialized_start=19
  _globals['_CONNECTIONREQUEST']._serialized_end=81
  _globals['_CONNECTIONRESPONSE']._serialized_start=83
  _globals['_CONNECTIONRESPONSE']._serialized_end=120
  _globals['_CHATMESSAGE']._serialized_start=122
  _globals['_CHATMESSAGE']._serialized_end=184
  _globals['_MESSAGEACK']._serialized_start=186
  _globals['_MESSAGEACK']._serialized_end=215
  _globals['_CLIENTID']._serialized_start=217
  _globals['_CLIENTID']._serialized_end=246
  _globals['_CHATSERVICE']._serialized_start=249
  _globals['_CHATSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
